# Generated by Django 6.0.4 on 2026-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_commentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('new_book', 'New Book'), ('system', 'System'), ('group', 'Group')], default='system', max_length=20),
        ),
    ]
